name: Publish CI

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Set tag version to ENV
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
      - uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Set artifact version to ENV
        run: echo "ARTIFACT_VERSION=v$(./gradlew -q getArtifactVersion)" >>$GITHUB_ENV
      - name: Compare tag and artifact versions
        if: ${{ env.TAG_VERSION != env.ARTIFACT_VERSION }}
        run: exit 1
      - name: Build and Publish with Gradle
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew library:publishAllPublicationsToMavenCentralRepository